[CalypsoAI - Scanner Outcome (Last 24h)]
search = index=main (source="calypsoai" OR source="f5-calypso-SIQ") sourcetype=calypsoai earliest=-24h@h latest=now | spath | eval scanner_outcome=coalesce(scanner_outcome, 'event.scanner_outcome') | eval outcome=coalesce(scanner_outcome, "unknown") | stats count by outcome | sort - count
dispatch.earliest_time = -24h@h
dispatch.latest_time = now
is_visible = 1

[CalypsoAI - Event Volume (Last 24h)]
search = index=main (source="calypsoai" OR source="f5-calypso-SIQ") sourcetype=calypsoai earliest=-24h@h latest=now | timechart span=15m count AS events
dispatch.earliest_time = -24h@h
dispatch.latest_time = now
is_visible = 1
